### PR TITLE
bug/231/fix regexp restore paren handling

### LINKED ISSUE #231: createRegExpRestore explodes with an unmatched parenthesis
Hey hey!

We just noticed this problem after upgrading Intl.  We see this failure sometimes in poltergeist and also seemed to be causing problems with our site loading in Safari:

```
Unhandled promise rejection SyntaxError: Invalid regular expression: unmatched parentheses
```

Printing out the evolution of the regex string it's trying to construct, it undergoes this path through the createRegExpRestore method before exploding when the end result `[\s\S]{26}(((((((())))))))[\s\S]{38})` has an unmatched `)` at the end.:

```
lastMatch:
function defineProperty() {
    [native code]
}
lm:
function defineProperty\(\) \{
    \[native code\]
\}
exprStr:
function defineProperty\(\) \{
    \[native code\]
\}
exprStr:
[\s\S]{52}
lastMatch:
function defineProperty\(\) \{
    \[native code\]
\}
lm:
function defineProperty\\\(\\\) \\\{
    \\\[native code\\\]
\\\}
has:
}
m:
}
lm:
function defineProperty\\\(\\\) \\\{
    \\\[native code\\\]
\\(\})
lm:
function defineProperty\\\(\\\) \\\{
    \\\[native code\\\]
\\(\})
lm:
\\\) \\\{
    \\\[native code\\\]
\\(\})
m:

lm:
()\\\) \\\{
    \\\[native code\\\]
\\(\})
lm:
()\\\) \\\{
    \\\[native code\\\]
\\(\})
lm:
)\\\) \\\{
    \\\[native code\\\]
\\(\})
m:

lm:
())\\\) \\\{
    \\\[native code\\\]
\\(\})
lm:
())\\\) \\\{
    \\\[native code\\\]
\\(\})
lm:
))\\\) \\\{
    \\\[native code\\\]
\\(\})
m:

lm:
()))\\\) \\\{
    \\\[native code\\\]
\\(\})
lm:
()))\\\) \\\{
    \\\[native code\\\]
\\(\})
lm:
)))\\\) \\\{
    \\\[native code\\\]
\\(\})
m:

lm:
())))\\\) \\\{
    \\\[native code\\\]
\\(\})
lm:
())))\\\) \\\{
    \\\[native code\\\]
\\(\})
lm:
))))\\\) \\\{
    \\\[native code\\\]
\\(\})
m:

lm:
()))))\\\) \\\{
    \\\[native code\\\]
\\(\})
lm:
()))))\\\) \\\{
    \\\[native code\\\]
\\(\})
lm:
)))))\\\) \\\{
    \\\[native code\\\]
\\(\})
m:

lm:
())))))\\\) \\\{
    \\\[native code\\\]
\\(\})
lm:
())))))\\\) \\\{
    \\\[native code\\\]
\\(\})
lm:
))))))\\\) \\\{
    \\\[native code\\\]
\\(\})
m:

lm:
()))))))\\\) \\\{
    \\\[native code\\\]
\\(\})
lm:
()))))))\\\) \\\{
    \\\[native code\\\]
\\(\})
lm:
)))))))\\\) \\\{
    \\\[native code\\\]
\\(\})
m:

lm:
())))))))\\\) \\\{
    \\\[native code\\\]
\\(\})
lm:
())))))))\\\) \\\{
    \\\[native code\\\]
\\(\})
lm:
))))))))\\\) \\\{
    \\\[native code\\\]
\\(\})
exprStr:
function defineProperty\\\((((((((())))))))\\\) \\\{
    \\\[native code\\\]
\\(\})
exprStr:
[\s\S]{26}(((((((())))))))[\s\S]{38})
```

### PR DESCRIPTION
**Pull request by mtlewis**
Fixes #231.  

Comments in line with the code explain the related issues.  The test that I added is failing in master, passing with the changes in this branch (though I haven't included the updated build in the PR).

### CODE REVIEW

File: src/util.js [hunk 1]
```diff
@@ -152,39 +152,49 @@ export function createRegExpRestore () {
...
                 // Else find the string in lm and escape & wrap it to capture it
                 else {
                     m = m.replace(esc, '\\$&');
-                    lm = lm.replace(m, '(' + m + ')');
+                    exprStr += lastMatch.substring(0, lastMatch.indexOf(m)) + '(';
+                    lastMatch = m + ')' + lastMatch.substring(lastMatch.indexOf(m) + m.length);
                 }
-
-                // Push it to the reg and chop lm to make sure further groups come after
-                arrPush.call(reg, lm.slice(0, lm.indexOf('(') + 1));
```
Comment (mtlewis) [inline src/util.js]: First significant problem with the previous implementation.  `lm.indexOf('(')` is looking for the paren we added on line 170, but it could also potentially catch escaped parens that occur earlier in the string.

File: src/util.js [hunk 2]
```diff
@@ -152,39 +152,49 @@ export function createRegExpRestore () {
...
 
-        let exprStr = arrJoin.call(reg, '') + lm;
+        exprStr += lastMatch;
 
         // Shorten the regex by replacing each part of the expression with a match
         // for a string of that exact length.  This is safe for the type of
         // expressions generated above, because the expression matches the whole
         // match string, so we know each group and each segment between capturing
         // groups can be matched by its length alone.
-        exprStr = exprStr.replace(/(\\\(|\\\)|[^()])+/g, (match) => {
```
Comment (mtlewis) [inline src/util.js]: Second significant problem with the code.  This second operation on `exprStr` takes a series of characters other than unescaped parentheses and replaces it with `[\s\S]{length}`.  This allows our RegEx to work with much longer input strings.   However, the prior version of this regex does not handle *un*escaped parentheses that come immediately after escaped backslashes.  The new version is much more complicated, but accounts for sequences of escaped and unescaped backslashes and parentheses.

Looking at it now, I think the whole thing will be much more maintainable if we stop using a RegEx here and instead iterate over the characters in `exprStr` and check for escaped characters and match groups character-by-character.  Happy to work on that tomorrow under this PR or a separate one post-merge.

Comment (mtlewis) [inline src/util.js]: @caridy: Just had a play around with implementing this bit of functionality via iteration rather than the existing regex-based approach.  You can see the changes [here](https://github.com/mtlewis/Intl.js/compare/bug/231/fix-regexp-restore-paren-handling...mtlewis:bug/231/iteration-based-regex-shortening?expand=1).  The iteration-based approach didn't turn out to be as clean as I was hoping it would be, so I'd propose we leave the regex-based approach in place.

**Comment by caridy** [comment]
@mtlewis let me know when this is ready for review.

**Comment by mtlewis** [comment]
@caridy hey! Its ready from my perspective :+1:

**Comment by caridy** [comment]
thanks @mtlewis, this is looking good!
